### ISSUE TITLE
Certificate verification error

### ISSUE THREAD

**Issue by hdumcke** [Tiryoh/ros2_setup_scripts_ubuntu#54]
when doing:

sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

we get an error:
curl: (60) SSL: no alternative certificate subject name matches target host name 'raw.githubusercontent.com'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

using 

 sudo curl --insecure -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
 
 is a workaround but insecure.
 
 I will subit a PR with this workaround for your review

**Comment by Tiryoh** [comment]
It seem like an error in curl (7.81.0-1ubuntu1.11), but curl (7.81.0-1ubuntu1.13) has already been released and fixed.

https://bugs.launchpad.net/ubuntu/+source/curl/+bug/2028191

https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/actions/runs/5570877578/attempts/2

<img width="1033" alt="スクリーンショット 2023-07-20 8 34 30" src="https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/assets/3256629/91ceedf9-e3e8-47fd-96e7-373c34c30ec8">


https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/actions/runs/5570877578/attempts/3

<img width="1041" alt="スクリーンショット 2023-07-20 8 35 03" src="https://github.com/Tiryoh/ros2_setup_scripts_ubuntu/assets/3256629/69cb6967-e604-4a12-ad21-002514087d66">

**Comment by Tiryoh** [comment]
I'm closing this issue because the underlying problem has been resolved.
