### ISSUE TITLE
Broken ROS 2 Documentation Links

### ISSUE THREAD

**Issue by CursedRock17** [Tiryoh/ros2_setup_scripts_ubuntu#63]
Around the docs for this package, there are various ROS 2 documentation links that are broken, mainly in part due to using index.ros.org opposed to docs.ros.org (where documentation is now hosted for each ROS package). [A search](https://github.com/search?q=repo%3ATiryoh%2Fros2_setup_scripts_ubuntu%20index.ros.org%2Fdoc&type=code) around the repo shows various spots in which the docs are wrong, for instance:

> https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Install-Debians/

should instead be:
> https://docs.ros.org/en/crystal/Installation/Linux-Install-Debians.html

I currently don't have the bandwidth to solve this, but it's a simple solution, perhaps great for new contributors.

**Comment by Tiryoh** [comment]
Hi @CursedRock17,

Thanks for your report! I'll update the link.
